[build]
  # Đường dẫn tương đối tính từ gốc của Repo hướng vào thư mục Frontend
  base = "fontend"
  
  # Lệnh build và thư mục đầu ra
  command = "npm run build"
  publish = "dist"

# Cấu hình chuyển hướng để tránh lỗi 404 khi F5 trang (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200